import type { IconType } from "react-icons";
import {
  GiBattleAxe, GiAxeSword, GiCrossedAxes, GiBatteredAxe, GiBroadsword,
  GiCrossedSwords, GiBloodySword, GiAncientSword, GiKatana, GiDaggers,
  GiPlainDagger, GiBowieKnife, GiBowArrow, GiCrossbow, GiArrowhead,
  GiArrowCluster, GiWarhammer, GiThorHammer, GiFlangedMace, GiSpikedMace,
  GiSpearHook, GiBarbedSpear, GiSpears, GiHalberd, GiFlail, GiWizardStaff,
  GiTrident, GiScythe, GiWhip, GiFist, GiPunch, GiSwordman, GiChakram,
  GiHalberdShuriken,
  GiBreastplate, GiArmorVest, GiChestArmor, GiShield, GiWingedShield,
  GiCheckedShield, GiEdgedShield, GiHelmet, GiCrestedHelmet, GiGauntlet,
  GiBoots, GiGloves, GiCloak, GiCape, GiShoulderArmor,
  GiBackpack, GiSwapBag, GiKnapsack, GiRopeCoil, GiTorch, GiLantern,
  GiCompass, GiTreasureMap, GiCoins, GiTwoCoins, GiMoneyStack, GiChest,
  GiOpenChest, GiLockedChest, GiLockpicks, GiKey, GiKeyLock, GiCutDiamond,
  GiRing, GiGemNecklace, GiHealthPotion, GiMagicPotion, GiPotionBall,
  GiWaterFlask, GiBubblingFlask, GiScrollUnfurled, GiScrollQuill, GiTiedScroll,
  GiOpenBook, GiBookCover, GiSpellBook, GiBookmarklet, GiQuillInk, GiQuill,
  GiInkSwirl, GiCandleLight, GiHandBag, GiMeat, GiRoastChicken, GiBread,
  GiWaterBottle, GiCampingTent, GiBandageRoll, GiHerbsBundle, GiMortar,
  GiPestleMortar, GiCauldron, GiCook, GiCampCookingPot,
  GiAnvil, GiAnvilImpact, GiHammerNails, GiCircularSaw, GiSickle, GiFishingHook,
  GiLyre, GiHarp, GiBanjo, GiGuitar, GiViolin, GiDrum, GiFlute, GiPanFlute,
  GiFireball, GiFire, GiCampfire, GiFrostfire, GiChainLightning, GiLightningArc,
  GiSparkles, GiWaterBolt, GiPoison, GiPoisonBottle, GiAcid, GiHealing,
  GiHealingShield, GiHeartPlus, GiHearts, GiBleedingHeart, GiCrystalWand,
  GiFairyWand, GiMagicPortal, GiPortal, GiWizardFace, GiMagicHat, GiHolySymbol,
  GiHolyGrail, GiAllSeeingEye, GiEyeShield, GiDeathSkull, GiSkullCrossedBones,
  GiBrain, GiMuscleUp, GiRun, GiFootprint, GiWalkingBoot,
  GiBullHorns, GiBull, GiCow, GiMinotaur, GiWolfHead, GiBearHead, GiDragonHead,
  GiSnake, GiRaven, GiEagleHead, GiOwl, GiCat, GiHorseHead, GiSpiderAlt,
  GiSkeleton, GiGhost, GiAngelWings, GiBatWing, GiPaw, GiClaws, GiFeather,
  GiCrown, GiStarFormation, GiRoundStar, GiDiceTwentyFacesTwenty,
  GiDiceSixFacesFive, GiMountains, GiOakLeaf, GiThreeLeaves, GiMushroom,
  GiSunflower, GiSun, GiMoon, GiCheckMark,
} from "react-icons/gi";

export type IconMeta = { name: string; cat: string; kw: string };

// name -> componente
export const ICON_MAP: Record<string, IconType> = {
  GiBattleAxe, GiAxeSword, GiCrossedAxes, GiBatteredAxe, GiBroadsword,
  GiCrossedSwords, GiBloodySword, GiAncientSword, GiKatana, GiDaggers,
  GiPlainDagger, GiBowieKnife, GiBowArrow, GiCrossbow, GiArrowhead,
  GiArrowCluster, GiWarhammer, GiThorHammer, GiFlangedMace, GiSpikedMace,
  GiSpearHook, GiBarbedSpear, GiSpears, GiHalberd, GiFlail, GiWizardStaff,
  GiTrident, GiScythe, GiWhip, GiFist, GiPunch, GiSwordman, GiChakram,
  GiHalberdShuriken, GiBreastplate, GiArmorVest, GiChestArmor, GiShield,
  GiWingedShield, GiCheckedShield, GiEdgedShield, GiHelmet, GiCrestedHelmet,
  GiGauntlet, GiBoots, GiGloves, GiCloak, GiCape, GiShoulderArmor, GiBackpack,
  GiSwapBag, GiKnapsack, GiRopeCoil, GiTorch, GiLantern, GiCompass,
  GiTreasureMap, GiCoins, GiTwoCoins, GiMoneyStack, GiChest, GiOpenChest,
  GiLockedChest, GiLockpicks, GiKey, GiKeyLock, GiCutDiamond, GiRing,
  GiGemNecklace, GiHealthPotion, GiMagicPotion, GiPotionBall, GiWaterFlask,
  GiBubblingFlask, GiScrollUnfurled, GiScrollQuill, GiTiedScroll, GiOpenBook,
  GiBookCover, GiSpellBook, GiBookmarklet, GiQuillInk, GiQuill, GiInkSwirl,
  GiCandleLight, GiHandBag, GiMeat, GiRoastChicken, GiBread, GiWaterBottle,
  GiCampingTent, GiBandageRoll, GiHerbsBundle, GiMortar, GiPestleMortar,
  GiCauldron, GiCook, GiCampCookingPot, GiAnvil, GiAnvilImpact, GiHammerNails,
  GiCircularSaw, GiSickle, GiFishingHook, GiLyre, GiHarp, GiBanjo, GiGuitar,
  GiViolin, GiDrum, GiFlute, GiPanFlute, GiFireball, GiFire, GiCampfire,
  GiFrostfire, GiChainLightning, GiLightningArc, GiSparkles, GiWaterBolt,
  GiPoison, GiPoisonBottle, GiAcid, GiHealing, GiHealingShield, GiHeartPlus,
  GiHearts, GiBleedingHeart, GiCrystalWand, GiFairyWand, GiMagicPortal,
  GiPortal, GiWizardFace, GiMagicHat, GiHolySymbol, GiHolyGrail, GiAllSeeingEye,
  GiEyeShield, GiDeathSkull, GiSkullCrossedBones, GiBrain, GiMuscleUp, GiRun,
  GiFootprint, GiWalkingBoot, GiBullHorns, GiBull, GiCow, GiMinotaur,
  GiWolfHead, GiBearHead, GiDragonHead, GiSnake, GiRaven, GiEagleHead, GiOwl,
  GiCat, GiHorseHead, GiSpiderAlt, GiSkeleton, GiGhost, GiAngelWings, GiBatWing,
  GiPaw, GiClaws, GiFeather, GiCrown, GiStarFormation, GiRoundStar,
  GiDiceTwentyFacesTwenty, GiDiceSixFacesFive, GiMountains, GiOakLeaf,
  GiThreeLeaves, GiMushroom, GiSunflower, GiSun, GiMoon, GiCheckMark,
};

// name -> categoría + palabras clave (español + inglés) para el buscador
export const ICON_INDEX: IconMeta[] = [
  // ---------- Armas ----------
  { name: "GiBattleAxe", cat: "Armas", kw: "hacha hacha de guerra hacha de batalla gran hacha greataxe axe" },
  { name: "GiAxeSword", cat: "Armas", kw: "hacha espada axe" },
  { name: "GiCrossedAxes", cat: "Armas", kw: "hachas cruzadas dos hachas axes" },
  { name: "GiBatteredAxe", cat: "Armas", kw: "hacha vieja hacha de mano axe" },
  { name: "GiBroadsword", cat: "Armas", kw: "espada mandoble espada larga sword" },
  { name: "GiCrossedSwords", cat: "Armas", kw: "espadas cruzadas combate ataque batalla swords" },
  { name: "GiBloodySword", cat: "Armas", kw: "espada sangrienta sangre sword" },
  { name: "GiAncientSword", cat: "Armas", kw: "espada antigua espada sword" },
  { name: "GiKatana", cat: "Armas", kw: "katana espada japonesa sword" },
  { name: "GiSwordman", cat: "Armas", kw: "espadachin guerrero espada sword" },
  { name: "GiDaggers", cat: "Armas", kw: "dagas puñales cuchillos daggers" },
  { name: "GiPlainDagger", cat: "Armas", kw: "daga puñal cuchillo dagger" },
  { name: "GiBowieKnife", cat: "Armas", kw: "cuchillo navaja knife" },
  { name: "GiBowArrow", cat: "Armas", kw: "arco flecha arco y flecha bow arrow" },
  { name: "GiCrossbow", cat: "Armas", kw: "ballesta crossbow" },
  { name: "GiArrowhead", cat: "Armas", kw: "punta de flecha flecha arrow" },
  { name: "GiArrowCluster", cat: "Armas", kw: "flechas carcaj arrows" },
  { name: "GiWarhammer", cat: "Armas", kw: "martillo de guerra mazo warhammer" },
  { name: "GiThorHammer", cat: "Armas", kw: "martillo mjolnir thor hammer" },
  { name: "GiFlangedMace", cat: "Armas", kw: "maza mace" },
  { name: "GiSpikedMace", cat: "Armas", kw: "maza con pinchos lucero del alba mace" },
  { name: "GiSpearHook", cat: "Armas", kw: "lanza pica spear" },
  { name: "GiBarbedSpear", cat: "Armas", kw: "lanza con pua arpon spear" },
  { name: "GiSpears", cat: "Armas", kw: "lanzas picas spears" },
  { name: "GiHalberd", cat: "Armas", kw: "alabarda halberd" },
  { name: "GiHalberdShuriken", cat: "Armas", kw: "alabarda arma de asta polearm" },
  { name: "GiFlail", cat: "Armas", kw: "mangual flail" },
  { name: "GiWizardStaff", cat: "Armas", kw: "baston vara caña bordón staff" },
  { name: "GiTrident", cat: "Armas", kw: "tridente trident" },
  { name: "GiScythe", cat: "Armas", kw: "guadaña hoz scythe" },
  { name: "GiWhip", cat: "Armas", kw: "latigo whip" },
  { name: "GiChakram", cat: "Armas", kw: "chakram disco arrojadizo" },
  { name: "GiFist", cat: "Armas", kw: "puño golpe sin armas desarmado fist unarmed" },
  { name: "GiPunch", cat: "Armas", kw: "puñetazo golpe puño punch" },

  // ---------- Armaduras ----------
  { name: "GiBreastplate", cat: "Armaduras", kw: "coraza peto armadura breastplate armor" },
  { name: "GiArmorVest", cat: "Armaduras", kw: "armadura chaleco armor" },
  { name: "GiChestArmor", cat: "Armaduras", kw: "armadura de pecho armor" },
  { name: "GiShoulderArmor", cat: "Armaduras", kw: "hombrera armadura pauldron armor" },
  { name: "GiShield", cat: "Armaduras", kw: "escudo shield defensa" },
  { name: "GiWingedShield", cat: "Armaduras", kw: "escudo alado shield" },
  { name: "GiCheckedShield", cat: "Armaduras", kw: "escudo shield" },
  { name: "GiEdgedShield", cat: "Armaduras", kw: "escudo shield" },
  { name: "GiHelmet", cat: "Armaduras", kw: "casco yelmo helmet" },
  { name: "GiCrestedHelmet", cat: "Armaduras", kw: "casco con cresta yelmo helmet" },
  { name: "GiGauntlet", cat: "Armaduras", kw: "guantelete manopla gauntlet" },
  { name: "GiGloves", cat: "Armaduras", kw: "guantes gloves" },
  { name: "GiBoots", cat: "Armaduras", kw: "botas calzado boots" },
  { name: "GiCloak", cat: "Armaduras", kw: "capa manto cloak" },
  { name: "GiCape", cat: "Armaduras", kw: "capa cape" },

  // ---------- Equipo ----------
  { name: "GiBackpack", cat: "Equipo", kw: "mochila petate backpack" },
  { name: "GiKnapsack", cat: "Equipo", kw: "mochila saco knapsack" },
  { name: "GiSwapBag", cat: "Equipo", kw: "bolsa saco bag" },
  { name: "GiHandBag", cat: "Equipo", kw: "bolsa bolsa de mano pouch bag" },
  { name: "GiRopeCoil", cat: "Equipo", kw: "cuerda soga rope" },
  { name: "GiTorch", cat: "Equipo", kw: "antorcha torch fuego luz" },
  { name: "GiLantern", cat: "Equipo", kw: "farol linterna lantern luz" },
  { name: "GiCandleLight", cat: "Equipo", kw: "vela candela candle luz" },
  { name: "GiCompass", cat: "Equipo", kw: "brujula compass" },
  { name: "GiTreasureMap", cat: "Equipo", kw: "mapa mapa del tesoro map" },
  { name: "GiCoins", cat: "Equipo", kw: "monedas oro dinero coins gold" },
  { name: "GiTwoCoins", cat: "Equipo", kw: "monedas dinero coins" },
  { name: "GiMoneyStack", cat: "Equipo", kw: "dinero monedas riqueza money" },
  { name: "GiChest", cat: "Equipo", kw: "cofre baul chest" },
  { name: "GiOpenChest", cat: "Equipo", kw: "cofre abierto tesoro chest" },
  { name: "GiLockedChest", cat: "Equipo", kw: "cofre cerrado con llave chest" },
  { name: "GiKey", cat: "Equipo", kw: "llave key" },
  { name: "GiKeyLock", cat: "Equipo", kw: "llave candado cerradura lock key" },
  { name: "GiLockpicks", cat: "Equipo", kw: "ganzuas herramientas de ladron lockpicks" },
  { name: "GiCutDiamond", cat: "Equipo", kw: "diamante gema joya gem diamond" },
  { name: "GiRing", cat: "Equipo", kw: "anillo sortija ring" },
  { name: "GiGemNecklace", cat: "Equipo", kw: "collar amuleto colgante gema necklace amulet" },
  { name: "GiHealthPotion", cat: "Equipo", kw: "pocion curacion vida potion" },
  { name: "GiMagicPotion", cat: "Equipo", kw: "pocion magica elixir potion" },
  { name: "GiPotionBall", cat: "Equipo", kw: "pocion frasco vial potion" },
  { name: "GiWaterFlask", cat: "Equipo", kw: "cantimplora frasco agua odre flask waterskin" },
  { name: "GiWaterBottle", cat: "Equipo", kw: "botella de agua cantimplora bottle" },
  { name: "GiBubblingFlask", cat: "Equipo", kw: "frasco burbujeante alquimia flask" },
  { name: "GiScrollUnfurled", cat: "Equipo", kw: "pergamino rollo scroll" },
  { name: "GiScrollQuill", cat: "Equipo", kw: "pergamino y pluma escrito scroll" },
  { name: "GiTiedScroll", cat: "Equipo", kw: "pergamino atado rollo scroll" },
  { name: "GiOpenBook", cat: "Equipo", kw: "libro abierto libro book" },
  { name: "GiBookCover", cat: "Equipo", kw: "libro tomo book" },
  { name: "GiSpellBook", cat: "Equipo", kw: "libro de conjuros grimorio spellbook" },
  { name: "GiBookmarklet", cat: "Equipo", kw: "marcador libro bookmark" },
  { name: "GiQuill", cat: "Equipo", kw: "pluma escribir quill" },
  { name: "GiQuillInk", cat: "Equipo", kw: "pluma y tinta escribir quill ink" },
  { name: "GiInkSwirl", cat: "Equipo", kw: "tinta mancha ink" },
  { name: "GiMeat", cat: "Equipo", kw: "carne comida racion meat food" },
  { name: "GiRoastChicken", cat: "Equipo", kw: "pollo asado comida banquete food" },
  { name: "GiBread", cat: "Equipo", kw: "pan comida racion bread food" },
  { name: "GiCampingTent", cat: "Equipo", kw: "tienda campamento tent camp" },
  { name: "GiBandageRoll", cat: "Equipo", kw: "vendas botiquin bandage" },
  { name: "GiHerbsBundle", cat: "Equipo", kw: "hierbas plantas kit de herboristeria herbs" },

  // ---------- Herramientas ----------
  { name: "GiAnvil", cat: "Herramientas", kw: "yunque herrero forja herramientas de herrero anvil smith" },
  { name: "GiAnvilImpact", cat: "Herramientas", kw: "yunque forja herrero anvil" },
  { name: "GiHammerNails", cat: "Herramientas", kw: "martillo y clavos carpinteria hammer" },
  { name: "GiCircularSaw", cat: "Herramientas", kw: "sierra serrucho carpinteria saw" },
  { name: "GiSickle", cat: "Herramientas", kw: "hoz herramienta sickle" },
  { name: "GiFishingHook", cat: "Herramientas", kw: "anzuelo pesca fishing hook" },
  { name: "GiMortar", cat: "Herramientas", kw: "mortero alquimia mortar" },
  { name: "GiPestleMortar", cat: "Herramientas", kw: "mortero y mano alquimia herbalismo mortar pestle" },
  { name: "GiCauldron", cat: "Herramientas", kw: "caldero alquimia pocima cauldron" },
  { name: "GiCampCookingPot", cat: "Herramientas", kw: "olla puchero cocina cooking pot" },
  { name: "GiCook", cat: "Herramientas", kw: "cocinero utiles de cocina cook chef" },
  { name: "GiLyre", cat: "Herramientas", kw: "lira instrumento musica bardo lyre music" },
  { name: "GiHarp", cat: "Herramientas", kw: "arpa instrumento musica harp music" },
  { name: "GiBanjo", cat: "Herramientas", kw: "banjo laud instrumento musica banjo lute" },
  { name: "GiGuitar", cat: "Herramientas", kw: "guitarra laud instrumento musica guitar lute" },
  { name: "GiViolin", cat: "Herramientas", kw: "violin instrumento musica violin" },
  { name: "GiDrum", cat: "Herramientas", kw: "tambor percusion instrumento drum" },
  { name: "GiFlute", cat: "Herramientas", kw: "flauta instrumento musica flute" },
  { name: "GiPanFlute", cat: "Herramientas", kw: "flauta de pan instrumento musica flute" },

  // ---------- Magia ----------
  { name: "GiFireball", cat: "Magia", kw: "bola de fuego fuego conjuro fireball fire" },
  { name: "GiFire", cat: "Magia", kw: "fuego llama fire flame" },
  { name: "GiCampfire", cat: "Magia", kw: "hoguera fuego campamento campfire" },
  { name: "GiFrostfire", cat: "Magia", kw: "hielo escarcha frio frost ice" },
  { name: "GiWaterBolt", cat: "Magia", kw: "agua chorro water" },
  { name: "GiChainLightning", cat: "Magia", kw: "rayo relampago electricidad lightning" },
  { name: "GiLightningArc", cat: "Magia", kw: "rayo relampago electricidad lightning" },
  { name: "GiSparkles", cat: "Magia", kw: "destellos chispas magia brillo sparkles magic" },
  { name: "GiPoison", cat: "Magia", kw: "veneno toxico poison" },
  { name: "GiPoisonBottle", cat: "Magia", kw: "veneno frasco toxico poison" },
  { name: "GiAcid", cat: "Magia", kw: "acido corrosivo acid" },
  { name: "GiHealing", cat: "Magia", kw: "curacion sanar salud vida healing" },
  { name: "GiHealingShield", cat: "Magia", kw: "curacion proteccion healing" },
  { name: "GiHeartPlus", cat: "Magia", kw: "curar vida corazon salud heal heart" },
  { name: "GiHearts", cat: "Magia", kw: "corazones vida amor hearts" },
  { name: "GiBleedingHeart", cat: "Magia", kw: "corazon sangre vida heart" },
  { name: "GiCrystalWand", cat: "Magia", kw: "varita cristal magia wand" },
  { name: "GiFairyWand", cat: "Magia", kw: "varita magica hada wand" },
  { name: "GiMagicPortal", cat: "Magia", kw: "portal teletransporte puerta magica portal" },
  { name: "GiPortal", cat: "Magia", kw: "portal dimension portal" },
  { name: "GiWizardFace", cat: "Magia", kw: "mago hechicero brujo wizard mage" },
  { name: "GiMagicHat", cat: "Magia", kw: "sombrero de mago magia hat wizard" },
  { name: "GiHolySymbol", cat: "Magia", kw: "simbolo sagrado clerigo divino holy symbol" },
  { name: "GiHolyGrail", cat: "Magia", kw: "caliz grial sagrado holy grail" },
  { name: "GiAllSeeingEye", cat: "Magia", kw: "ojo que todo lo ve vision adivinacion eye" },
  { name: "GiEyeShield", cat: "Magia", kw: "ojo proteccion vision eye" },

  // ---------- Habilidades / rasgos ----------
  { name: "GiBullHorns", cat: "Habilidades", kw: "cuernos embestida carga toro bull horns charge" },
  { name: "GiMuscleUp", cat: "Habilidades", kw: "musculo fuerza bicep furia strength muscle" },
  { name: "GiRun", cat: "Habilidades", kw: "correr velocidad carrera huir run speed" },
  { name: "GiWalkingBoot", cat: "Habilidades", kw: "andar caminar viaje bota walk" },
  { name: "GiFootprint", cat: "Habilidades", kw: "huella rastro rastrear supervivencia footprint track" },
  { name: "GiBrain", cat: "Habilidades", kw: "cerebro inteligencia mente brain mind" },
  { name: "GiPaw", cat: "Habilidades", kw: "huella pata animal bestia paw" },
  { name: "GiClaws", cat: "Habilidades", kw: "garras zarpa ataque natural claws" },
  { name: "GiFeather", cat: "Habilidades", kw: "pluma ligereza caida feather" },
  { name: "GiAngelWings", cat: "Habilidades", kw: "alas volar vuelo angel wings fly" },
  { name: "GiBatWing", cat: "Habilidades", kw: "ala de murcielago volar wing" },
  { name: "GiHealthPotionAbility", cat: "Habilidades", kw: "" }, // (placeholder no usado)

  // ---------- Criaturas ----------
  { name: "GiMinotaur", cat: "Criaturas", kw: "minotauro toro bestia minotaur" },
  { name: "GiBull", cat: "Criaturas", kw: "toro bestia bull" },
  { name: "GiCow", cat: "Criaturas", kw: "vaca res cow" },
  { name: "GiWolfHead", cat: "Criaturas", kw: "lobo bestia wolf" },
  { name: "GiBearHead", cat: "Criaturas", kw: "oso bestia bear" },
  { name: "GiDragonHead", cat: "Criaturas", kw: "dragon draconido dragon" },
  { name: "GiSnake", cat: "Criaturas", kw: "serpiente vibora snake" },
  { name: "GiRaven", cat: "Criaturas", kw: "cuervo pajaro ave raven crow bird" },
  { name: "GiEagleHead", cat: "Criaturas", kw: "aguila ave pajaro eagle bird" },
  { name: "GiOwl", cat: "Criaturas", kw: "buho lechuza ave owl" },
  { name: "GiCat", cat: "Criaturas", kw: "gato felino cat" },
  { name: "GiHorseHead", cat: "Criaturas", kw: "caballo montura horse" },
  { name: "GiSpiderAlt", cat: "Criaturas", kw: "araña bicho spider" },
  { name: "GiSkeleton", cat: "Criaturas", kw: "esqueleto no muerto skeleton undead" },
  { name: "GiGhost", cat: "Criaturas", kw: "fantasma espectro ghost" },
  { name: "GiDeathSkull", cat: "Criaturas", kw: "calavera craneo muerte skull death" },
  { name: "GiSkullCrossedBones", cat: "Criaturas", kw: "calavera huesos veneno muerte skull" },

  // ---------- Naturaleza ----------
  { name: "GiMountains", cat: "Naturaleza", kw: "montañas montaña sierra mountains" },
  { name: "GiOakLeaf", cat: "Naturaleza", kw: "hoja roble naturaleza leaf" },
  { name: "GiThreeLeaves", cat: "Naturaleza", kw: "hojas plantas naturaleza leaves" },
  { name: "GiMushroom", cat: "Naturaleza", kw: "seta hongo mushroom" },
  { name: "GiSunflower", cat: "Naturaleza", kw: "flor girasol planta flower" },
  { name: "GiSun", cat: "Naturaleza", kw: "sol dia luz sun" },
  { name: "GiMoon", cat: "Naturaleza", kw: "luna noche moon" },

  // ---------- Varios ----------
  { name: "GiCrown", cat: "Varios", kw: "corona rey noble crown" },
  { name: "GiStarFormation", cat: "Varios", kw: "estrella star" },
  { name: "GiRoundStar", cat: "Varios", kw: "estrella star favorito" },
  { name: "GiDiceTwentyFacesTwenty", cat: "Varios", kw: "dado d20 dado de veinte dice d20" },
  { name: "GiDiceSixFacesFive", cat: "Varios", kw: "dado d6 dado dice" },
  { name: "GiCheckMark", cat: "Varios", kw: "check marca hecho tick" },
];

// Quitar entradas placeholder sin componente real
const VALID = ICON_INDEX.filter((m) => ICON_MAP[m.name]);

export const CATEGORIES: string[] = Array.from(new Set(VALID.map((m) => m.cat)));

function strip(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "");
}

// Índice de búsqueda con texto normalizado (sin acentos)
const SEARCH = VALID.map((m) => ({
  ...m,
  norm: strip(m.kw + " " + m.name),
}));

export function searchIcons(query: string, cat?: string): IconMeta[] {
  const q = strip(query.trim());
  let list = SEARCH;
  if (cat) list = list.filter((m) => m.cat === cat);
  if (!q) return list;
  const terms = q.split(/\s+/);
  return list.filter((m) => terms.every((t) => m.norm.includes(t)));
}

export const ALL_ICONS: IconMeta[] = VALID;
